# Ansible playbook to alter Alfresco installation to allow remote debugging
#
# Author: Greg Green <gregory.p.green@boeing.com>

- hosts: tomcat-servers
  vars:
    jvm_debug_port: 8000
  tasks:

  - name: stop alfresco
    command systemctl stop tomcat-openmbee
    become: yes

  - name: add JVM debugging to tomcat environment file
    lineinfile:
      dest={{ tomcat_dir }}/bin/setenv.sh
      regexp="-agentlib:jdwp"
      insertafter="java.rmi.server.logCalls=true" 
      line=CATALINA_OPTS="$CATALINA_OPTS -agentlib:jdwp=transport=dt_socket,suspend=n,server=y,address={{ jvm_debug_port }}"
      backup=yes
    become: yes

  - name: start alfresco
    service: name=tomcat state=started
    become: yes

  - name: ensure firewall is configured to allow http traffic
    command: firewall-cmd --zone=public --permanent --add-port={{ jvm_debug_port }}/tcp
    become: yes

  - name: restart firewall
    command: systemctl restart firewalld
    become: yes

